version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  target-branch: master
  ignore:
  - dependency-name: rails
    versions:
    - 6.1.3.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  target-branch: master
