require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/migrate/**
    - bin/**/*
    - node_modules/**/*
    - vendor/bundle/**/*
    - config/**/*
    - config.ru

Style/Documentation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/FilePath:
  Exclude:
    - config/environments/development.rb

Style/GlobalStdStream:
  Exclude:
    - config/environments/production.rb

Style/RedundantFetchBlock:
  Exclude:
    - config/puma.rb

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
