name: Deploy

on:
  workflow_run:
    workflows: ["Jest specs", "JS lint", "Rubocop", "Ruby tests", "System tests"]
    branches: [master]
    types:
      - completed
      - requested

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: "edu.depetris.00@gmail.com"
